# Generated by Django 4.1.4 on 2023-01-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employer_owner_employee_employer_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='An',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_an', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'an',
            },
        ),
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('an', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('grupa', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'grupa',
            },
        ),
        migrations.CreateModel(
            name='Materie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materie',
            },
        ),
        migrations.CreateModel(
            name='Orar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.an')),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.grupa')),
                ('materie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.materie')),
            ],
            options={
                'db_table': 'orar',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CNP', models.CharField(max_length=13)),
                ('nume_profesor', models.CharField(max_length=15)),
                ('prenume_profesor', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_sala', models.CharField(max_length=10)),
                ('nume_sala', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Zi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nume_zi', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'zi',
            },
        ),
        migrations.RemoveField(
            model_name='employer',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.AddField(
            model_name='orar',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.profesor'),
        ),
        migrations.AddField(
            model_name='orar',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.sala'),
        ),
        migrations.AddField(
            model_name='orar',
            name='zi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.zi'),
        ),
    ]
