# Generated by Django 4.1.4 on 2023-01-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_an_grupa_materie_orar_profesor_sala_zi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='an',
            options={'verbose_name_plural': 'Ani'},
        ),
        migrations.AlterModelOptions(
            name='grupa',
            options={'verbose_name_plural': 'Grupe'},
        ),
        migrations.AlterModelOptions(
            name='materie',
            options={'verbose_name_plural': 'Materii'},
        ),
        migrations.AlterModelOptions(
            name='orar',
            options={'verbose_name_plural': 'Orare'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesori'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name_plural': 'Sali'},
        ),
        migrations.AlterModelOptions(
            name='zi',
            options={'verbose_name_plural': 'Zile'},
        ),
        migrations.AlterField(
            model_name='grupa',
            name='grupa',
            field=models.CharField(max_length=5),
        ),
    ]
