# Generated by Django 4.1.4 on 2023-01-21 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_an_options_alter_grupa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orar',
            name='inceput_ora',
            field=models.TimeField(default='0:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orar',
            name='sfarsit_ora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
