# Generated by Django 4.1.4 on 2023-01-22 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_orar_inceput_ora_orar_sfarsit_ora'),
    ]

    operations = [
        migrations.AddField(
            model_name='materie',
            name='nume_materie',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
